#!/bin/bash
#SBATCH -J RM_rrna
#SBATCH -p RM-shared
#SBATCH -o RM_rrna.txt
#SBATCH -e RM_rrna.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ha2606@columbia.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=5
#SBATCH --cpus-per-task=8
#SBATCH --time=47:00:00

module load anaconda3
conda activate mapping_env
module load bbmap/39.01
module load FastQC/0.11.9

cd #insert path to trimmed reads that need rrna removed
BASE_DIR=$( realpath ..)
REF_DIR="${BASE_DIR}/reference" #path to whereved the SortmeRNA_rRNA_db file is

# BBduk to remove rRNA

for infile in *1_noERCC.fastq.gz
do
  base=$(basename ${infile} 1_noERCC.fastq.gz)
  bbduk.sh threads=8 in=${infile} in2=${base}2_noERCC.fastq.gz k=31 ref=${REF_DIR}/smr_v4.3_default_db.fasta \
  out1=${base}1_no_rRNAs.fastq.gz out2=${base}2_no_rRNAs.fastq.gz minlength=60
done

# FASTQC

mkdir FASTQC_After_bbduk_no_rRNAs

for i in $(find . -name "*no_rRNAs.fastq.gz");do fastqc -o FASTQC_After_bbduk_no_rRNAs $i; done
