#!/bin/bash
#SBATCH -p RM-shared
#SBATCH -o rna_output_%j.txt
#SBATCH -e rna_output_%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ha2606@columbia.edu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=22
#SBATCH --time=48:00:00
#SBATCH --mem=10Gb

#use to combine raw fasta fiels if they came back from processing and each lane is a separate file


cd #insert path to files

for i in $(find ./ -type f -name "*.fastq.gz" | while read F; do basename $F | rev | cut -c 22- | rev; done | sort | uniq)

    do echo "Merging R1"

cat "$i"_L00*_R1_001.fastq.gz > "$i"_R1.fastq.gz

       echo "Merging R2"

cat "$i"_L00*_R2_001.fastq.gz > "$i"_R2.fastq.gz

done;


mkdir ./raw_reads

mv ./*L00* ./raw_reads
