#!/bin/bash
#SBATCH -J downsample
#SBATCH -p RM-shared
#SBATCH -o downsample%j.log
#SBATCH -e downsample%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ha2606@columbia.edu
#SBATCH -N 1
#SBATCH --cpus-per-task=16
#SBATCH --ntasks-per-node=1
#SBATCH --time=48:00:00

#set wd
cd #location of files to downsample

#open bbduk
module load anaconda3
conda activate mapping_env
module load bbmap/39.01

# BBduk to downsample a large sample (ID: SM046, 86M reads)

reformat.sh in1=SM049_R1_noERCC.fastq in2=SM049_R2_noERCC.fastq out1=SM049_R1_noERCC_downsample.fastq \
 out2=SM049_R2_noERCC_downsample.fastq samplerate=0.7

#in1 and in2 are your input files
#out1 and out2 are the downsampled outputs
#samplerate=0.7 means to sample 70% of reads
